# Generated by Django 5.2 on 2025-05-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_telegram', models.CharField(max_length=200)),
                ('telegram_id', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(default='@', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=30)),
                ('time_lesson', models.TimeField()),
                ('theory_studied', models.BooleanField()),
                ('date_exam_theory', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=15)),
                ('car_brand', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('berth_day', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('consider', 'рассматривается'), ('accept', 'принят')], default='рассматривается', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TimeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_begin', models.TimeField()),
                ('work_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('berth_day', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('consider', 'рассматривается'), ('accept', 'принят')], default='рассматривается', max_length=30)),
                ('fk_group_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_school.grouptheory')),
            ],
        ),
        migrations.AddField(
            model_name='grouptheory',
            name='fk_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driving_school.teacher'),
        ),
        migrations.CreateModel(
            name='Driving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_driving', models.DateTimeField()),
                ('errors', models.IntegerField()),
                ('fk_school_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='driving_school.schoolcar')),
                ('fk_status_lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driving_school.statuslesson')),
                ('fk_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='driving_school.student')),
                ('fk_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='driving_school.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='fk_time_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_school.timework'),
        ),
    ]
