# Generated by Django 5.2 on 2025-05-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTheory',
            fields=[
                ('id_grouptheory', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_group', models.CharField(max_length=30)),
                ('time_lesson', models.TimeField()),
                ('theory_studied', models.BooleanField(default=False)),
                ('date_exam_theory', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Moderators',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('berth_day', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('consider', 'рассматривается'), ('accept', 'принят')], default='рассматривается', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('berth_day', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('consider', 'рассматривается'), ('accept', 'принят')], default='рассматривается', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('berth_day', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('consider', 'рассматривается'), ('accept', 'принят')], default='рассматривается', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeWork',
            fields=[
                ('id_timework', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('work_begin', models.TimeField()),
                ('work_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_grouptheory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driving_school.grouptheory')),
                ('telegram_id_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driving_school.student')),
            ],
        ),
        migrations.AddField(
            model_name='grouptheory',
            name='telegram_id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driving_school.teacher'),
        ),
        migrations.CreateModel(
            name='Driving',
            fields=[
                ('id_driving', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('datetime_driving', models.DateTimeField()),
                ('errors', models.IntegerField()),
                ('telegram_id_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='driving_school.student')),
                ('telegram_id_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='driving_school.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='fk_time_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driving_school.timework'),
        ),
    ]
