# Generated by Django 5.2 on 2025-05-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='username_telegram',
        ),
    ]
