# Generated by Django 5.2 on 2025-05-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driving',
            name='telegram_id_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='driving_school.student', unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='telegram_id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driving_school.student', unique=True),
        ),
        migrations.AlterField(
            model_name='grouptheory',
            name='telegram_id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driving_school.teacher', unique=True),
        ),
    ]
