# Generated by Django 5.2 on 2025-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0002_alter_driving_telegram_id_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptheory',
            name='name_group',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
