# Generated by Django 5.2 on 2025-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0002_remove_commission_username_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('consider', 'рассматривается'), ('accept', 'принят')], default='рассматривается', max_length=30),
        ),
        migrations.AlterField(
            model_name='commission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
