# Generated by Django 5.2 on 2025-05-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0003_alter_grouptheory_name_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='telegram_id_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='driving_school.student'),
        ),
    ]
