# Generated by Django 5.2 on 2025-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0004_alter_groups_telegram_id_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderators',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
        migrations.AlterField(
            model_name='moderators',
            name='is_active',
            field=models.IntegerField(choices=[(-1, 'Не состоит'), (0, 'рассматривается'), (1, 'действует')], default=(-1, 'Не состоит')),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.IntegerField(choices=[(-1, 'Не состоит'), (0, 'рассматривается'), (1, 'действует')], default=(-1, 'Не состоит')),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.IntegerField(choices=[(-1, 'Не состоит'), (0, 'рассматривается'), (1, 'действует')], default=(-1, 'Не состоит')),
        ),
    ]
