# Generated by Django 5.2 on 2025-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0005_remove_moderators_status_remove_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderators',
            name='is_active',
            field=models.IntegerField(choices=[(-1, 'Не состоит'), (0, 'рассматривается'), (1, 'действует')], default=(0, 'рассматривается')),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.IntegerField(choices=[(-1, 'Не состоит'), (0, 'рассматривается'), (1, 'действует')], default=(0, 'рассматривается')),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.IntegerField(choices=[(-1, 'Не состоит'), (0, 'рассматривается'), (1, 'действует')], default=(0, 'рассматривается')),
        ),
    ]
