# Generated by Django 5.2 on 2025-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0006_alter_moderators_is_active_alter_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driving',
            name='errors',
            field=models.IntegerField(default=-1),
        ),
    ]
