# Generated by Django 5.2 on 2025-05-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id_courses', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalMaterials',
            fields=[
                ('id_ed_materials', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('id_courses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id_certificate', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('id_courses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy.courses')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy.student')),
            ],
        ),
    ]
