# Generated by Django 5.2 on 2025-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_educationalmaterials_id_ed_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalmaterials',
            name='id_ed_materials',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
